I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 108, in script call
    call check from _call_check
  File "game/script.rpy", line 77, in script
    if not presis.ok:
  File "game/script.rpy", line 77, in <module>
    if not presis.ok:
NameError: name 'presis' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 108, in script call
    call check from _call_check
  File "game/script.rpy", line 77, in script
    if not presis.ok:
  File "D:\renpy\renpy-6.99.13-sdk\renpy\ast.py", line 1762, in execute
    if renpy.python.py_eval(condition):
  File "D:\renpy\renpy-6.99.13-sdk\renpy\python.py", line 1944, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\renpy\renpy-6.99.13-sdk\renpy\python.py", line 1937, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 77, in <module>
    if not presis.ok:
NameError: name 'presis' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
버드나무 꽃 만개할 그날까지 1.1
Wed Jun 05 12:38:24 2019
