I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 131, in script call
    call check from _call_check
  File "game/script.rpy", line 101, in script call
    call game3 from _call_game3
  File "game/script.rpy", line 1852, in script call
    call afterreset from _call_afterreset
  File "game/afterreset.rpy", line 13, in script call
    extend "\n음... 너무 강압적이었던 거려나?"
  File "renpy/common/00console.rpy", line 807, in script call
    python in _console:
NameError: name 'centor' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 131, in script call
    call check from _call_check
  File "game/script.rpy", line 101, in script call
    call game3 from _call_game3
  File "game/script.rpy", line 1852, in script call
    call afterreset from _call_afterreset
  File "game/afterreset.rpy", line 13, in script call
    extend "\n음... 너무 강압적이었던 거려나?"
  File "renpy/common/00console.rpy", line 807, in script call
    python in _console:
  File "lib/windows-i686/<string>", line 1, in script
  File "C:\renpy-7.2.2-sdk\renpy\ast.py", line 1181, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\renpy-7.2.2-sdk\renpy\ast.py", line 1140, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\renpy-7.2.2-sdk\renpy\python.py", line 1990, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\renpy-7.2.2-sdk\renpy\python.py", line 1983, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "lib/windows-i686/<string>", line 1, in <module>
NameError: name 'centor' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.0.271
버드나무 꽃 만개할 그날까지 1.1.2
Mon Sep 23 15:33:32 2019
